# Used for plugin debugging
# Check .vscode/launch.json for a debug task to run
version: '3.7'

services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile-debug
      args:
        grafana_version: ${GRAFANA_VERSION:-9.5.13}
        github_token: ${GITHUB_TOKEN}
        arch: ${ARCH:-amd64} # Use arm64 on Apple silicon Mac
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    container_name: mongodb-datasource
    ports:
      - "3000:3000"
      - "2345:2345" # used to connect debugger
    volumes:
      - ./:/var/lib/grafana/plugins/grafana-mongodb-datasource
      - ./data/grafana-oss:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT
